### ISSUE TITLE
I'm behind a Firewall

### ISSUE THREAD

**Issue by marcioAlmada** [TeamRemote/remote-sublime#10]
Silly question ahead.

Nobody could connect with me. Do I need to open a specific port? What port?

Cheers!

**Comment by marcioAlmada** [comment]
OK, I can see in console it's port 12345. Can I change the default port? :)

**Comment by hawkw** [comment]
The host currently listens for a remote connection on port `12345`, so if you open that, you should be able to host. Eventually, the host port will be set in a configuration file, but I haven't gotten around to it yet.

**Comment by hawkw** [comment]
You kinda beat me to it there. If you'd like the ability to set the host port in a config file, that's on my to-do list - see issue #8.

My main dev environment is kind of bricked at the moment, though, so it may be a few days while I wait for some computer parts. If you can't wait and you wanna add that functionality yourself, go ahead and fork the repo - I'd be happy to merge in any changes you make. It shouldn't be much work if you know the Sublime API.

**Comment by marcioAlmada** [comment]
:+1:
