### ISSUE TITLE
Add support for encrypted connections between peers

### ISSUE THREAD

**Issue by saxbophone** [TeamRemote/remote-sublime#13]
For security considerations —perhaps diffie-helman can be used to negotiate a shared session key

**Comment by hawkw** [comment]
Hi @saxbophone, this project is not actively maintained (and I don't think it sees much actual use). However, if you're interested in making it more secure, I'd happily accept a PR!

**Comment by saxbophone** [comment]
Hi @hawkw —thanks for mentioning that, I feared this might be the case.

Thanks, I'll keep this in mind if I ever look into adding this myself!
